name: Commit

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ inputs.message }}
        commit_user_name: Mihai Fufezan
        commit_user_email: fufexan@protonmail.com
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
