name: Build man pages

on:
  workflow_dispatch:
  push:
    paths:
      - docs/**
    branches:
      - 'main'

jobs:
  main:
    name: Build man pages
    runs-on: ubuntu-latest
    steps:
    - name: Install deps
      run: sudo apt install pandoc
    - name: Clone repository
      uses: actions/checkout@v3
      # Not needed
      # with:
      #   submodules: recursive
    - name: Build man pages
      run: make man

  push:
    uses: ./.github/workflows/commit.yml
    with:
      message: "[gha] build man pages"
