name: "Nix update"

on:
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  update:
    uses: ./.github/workflows/nix.yml
    with:
      command: nix/update-inputs.sh

  build:
    needs: update
    uses: ./.github/workflows/nix-build.yml

  build-waybar:
    needs: update
    uses: ./.github/workflows/nix.yml
    with:
      command: nix build -L .#waybar-hyprland

  push:
    needs: [build, build-waybar]
    uses: ./.github/workflows/commit.yml
    with:
      message: "Nix: bump inputs"
